version: '3.8'

services:
  vector_db:
    image: pgvector/pgvector:pg18
    container_name: pgvector-db
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/init_test_db.sh:/init_test_db.sh

volumes:
  pgdata:
